name = "linkedin-dashboard-cloudflare"
compatibility_date = "2024-06-05"

# ✅ Tell Pages where the built site will be
pages_build_output_dir = ".vercel/output/static"

[vars]
# LINKEDIN_CLIENT_ID = ""
# LINKEDIN_CLIENT_SECRET = ""
