name = "linkedin-dashboard-cloudflare"
compatibility_date = "2024-06-05"

# MUST specify where the built static assets live
pages_build_output_dir = ".vercel/output/static"

# Optionally define compatibility flags if you're using new features
compatibility_flags = ["nodejs_compat"]

[vars]
# Define your secrets or leave placeholders (set in Pages UI later)
# LINKEDIN_CLIENT_ID = ""
# LINKEDIN_CLIENT_SECRET = ""
