name = "linkedin-dashboard-cloudflare"
compatibility_date = "2024-06-05"

[vars]
# Add your LinkedIn secrets in the Cloudflare Pages dashboard (Project Settings → Environment Variables)
# LINKEDIN_CLIENT_ID = ""
# LINKEDIN_CLIENT_SECRET = ""
