name = "linkedin-dashboard-cloudflare"
compatibility_date = "2024-06-05"

# Required so Pages knows where to serve from
pages_build_output_dir = ".vercel/output/static"

[vars]
# LINKEDIN_CLIENT_ID = ""
# LINKEDIN_CLIENT_SECRET = ""
